; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Sat Mar 04 2017 15:46:00 GMT+0100 (W. Europe Standard Time)

G28		;home all
G91		;relative mode
G1 Z4 F200	;move Z up 4mm for clearence
G90		;absolute mode
M401		;lower probe
G29 S2		;clear bed compensation
G29		;run auto bed mesh level
M402		;retract probe
G1 X10 Y100 F5000